:ldap:
  :host:            #10.10.10.10
  :domain:          # base domain
  :credentials:
    :un:            # ldap_server username
    :pw:            # ldap_server password
  :schema:
    :filter: "computer" # default filter
:amp:
  :host:            # AMP API URL
  :api:
    :third_party:   # Third Party Code
    :key:           # API Key
    :version: "v1"  # Default API version
