:ldap:
  :host: "10.83.144.69"
  :domain: "2k8sso.local"
  :credentials:
    :un: "administrator"
    :pw: "gt(4DMpkgZrFay9MC2Yy"
  :schema:
    :filter: "computer"
    :attributes: "cn"
:amp:
  :host: "localhost:3000"
 	:email: "chwoznia@cisco.com"
	:api:
 		:third_party: "338ee569217d94555fc2"
		:key: "583cf634-5893-42d3-8005-c91a2039c2f9"
		:version: "v1"
