:ldap:
  :host: "10.83.144.69"
  :domain: "2k8sso.local"
  :credentials:
    :un: "administrator"
    :pw: "gt(4DMpkgZrFay9MC2Yy"
  :schema:
    :filter: "computer"
:amp:
  :host: "http://api.qa1.immunet.com"
  :api:
    :third_party: "e834ecb5ed978b9b287c"
    :key: "ce6ca488-04e3-4457-b921-01aba112ab8b"
    :version: "v1"
